-- local command_center = require("command_center")
-- local noremap = {noremap = true}
-- local silent_noremap = {noremap = true, silent = true}
--
-- command_center.add({
--
--   -- ################################################
--   -- # Tools
--   -- ################################################
--
--   -- ################################################
--   -- # BASIC
--   -- ################################################
--
--   -- ################################################
--   -- # MOTIVATION
--   -- ################################################
--
--   -- ################################################
--   -- # Key Maps
--   -- ################################################
--
--   -- ################################################
--   -- # UI
--   -- ################################################
--
--   -- ################################################
--   -- # Completions & Linters
--   -- ################################################
--   -- {
--   --   -- If no descirption is specified, cmd is used to replace descirption by default
--   --   -- You can change this behavior in setup()
--   --   cmd = "<CMD>Telescope find_files<CR>",
--   --   keys = { "n", "<leader>ff", noremap },
--   -- }, {
--   --   -- If no keys are specified, no keymaps will be displayed nor set
--   --   desc = "Find hidden files",
--   --   cmd = "<CMD>Telescope find_files hidden=true<CR>",
--   -- }, {
--   --   -- You can specify multiple keys for the same cmd ...
--   --   desc = "Show document symbols",
--   --   cmd = "<CMD>Telescope lsp_document_symbols<CR>",
--   --   keys = {
--   --     {"n", "<leader>ss", noremap},
--   --     {"n", "<leader>ssd", noremap},
--   --   },
--   -- }, {
--   --   -- ... and for different modes
--   --   desc = "Show function signaure (hover)",
--   --   cmd = "<CMD>lua vim.lsp.buf.hover()<CR>",
--   --   keys = {
--   --     {"n", "K", silent_noremap },
--   --     {"i", "<C-k>", silent_noremap },
--   --   }
--   -- },
--   -- {
--   --   -- You can pass in a key sequences as if you would type them in nvim
--   --   desc = "My favorite key sequence",
--   --   cmd = "A  -- Add a comment at the end of a line",
--   --   keys = {"n", "<leader>Ac", noremap}
--   -- },
--   -- {
--   --   -- You can also pass in a lua functions as cmd
--   --   -- NOTE: binding lua funciton to a keymap requires nvim 0.7 and above
--   --   desc = "Run lua function",
--   --   cmd = function() print("ANONYMOUS LUA FUNCTION") end,
--   --   keys = {"n", "<leader>alf", noremap},
--   -- },
-- })
